DROP TABLE IF EXISTS IF CASCADE;
DROP TABLE IF EXISTS prontuario_documentos CASCADE;
DROP TABLE IF EXISTS atestados CASCADE;
DROP TABLE IF EXISTS prescricoes CASCADE;
DROP TABLE IF EXISTS evolucoes CASCADE;
