DROP TABLE IF EXISTS IF CASCADE;
DROP TABLE IF EXISTS folhas_pj CASCADE;
DROP TABLE IF EXISTS folhas_clt CASCADE;
DROP TABLE IF EXISTS funcionarios_pj CASCADE;
DROP TABLE IF EXISTS funcionarios_clt CASCADE;
