DROP TABLE IF EXISTS IF CASCADE;
DROP TABLE IF EXISTS comodatos CASCADE;
DROP TABLE IF EXISTS inventario_contagens CASCADE;
DROP TABLE IF EXISTS inventarios CASCADE;
DROP TABLE IF EXISTS movimentacoes_estoque CASCADE;
DROP TABLE IF EXISTS itens_estoque CASCADE;
