DROP TABLE IF EXISTS IF CASCADE;
DROP TABLE IF EXISTS notification_settings CASCADE;
DROP TABLE IF EXISTS agenda_exceptions CASCADE;
DROP TABLE IF EXISTS reservas CASCADE;
DROP TABLE IF EXISTS consultas CASCADE;
DROP TABLE IF EXISTS sala_recursos CASCADE;
DROP TABLE IF EXISTS sala_especialidades CASCADE;
DROP TABLE IF EXISTS salas CASCADE;
